### ISSUE TITLE
Issues with nativescript 3 and android

### ISSUE THREAD

**Issue by pitAlex** [EddyVerbruggen/nativescript-appversion#11]
Hi,

With the latest nativescript version I am seeing the following errors whenever I run the app in android:

JS: Debug: TypeError: Cannot read property 'getPackageName' of undefined
JS: Debug: TypeError: Cannot read property 'getPackageManager' of undefined

**Comment by EddyVerbruggen** [comment]
I just tried it with 3.0.0, no problem with `getVersionName` on Android. Can you share your code? Perhaps you're calling it too early.. can you try moving the logic around just to check that assumption?

**Comment by pitAlex** [comment]
I am using getVersionNameSync() and getAppIdSync(), but you are right. Moving the code inside 
application.launchEvent callback made the errors go away.

**Comment by shiv19** [comment]
@EddyVerbruggen 
I get this when I try to get version code on android (Latest N)
`Error in appversion.getVersionCode: TypeError: Cannot read property 'getPackageManager' of undefined`
