### ISSUE TITLE
Support for "markingMode" flag

### ISSUE THREAD

**Issue by RinkalGohel** [EddyVerbruggen/nativescript-appversion#12]
Hi there! 

Wanted to know whether your plugin will still be working fine if I add the flag of 'markingMode' set to 'none' in package.json file, as mentioned in one of the blogs of NativeScript release? 

Here is the link of the blog where the reference is made for the same: https://www.nativescript.org/blog/announcing-the-release-of-nativescript-3.2

Looking forward to an early reply. Thank you!

**Comment by EddyVerbruggen** [comment]
Can you please not crosspost a question like this in at least 4 repos?

This app has a few of those plugins and markingmode set to what you could easily try yourself: 

https://github.com/EddyVerbruggen/nativescript-pluginshowcase
