### ISSUE TITLE
context.getPackageManager is not a function error

### ISSUE THREAD

**Issue by Daxito** [EddyVerbruggen/nativescript-appversion#3]
I am getting this error for Android, real device:

context.getPackageManager is not a function error

Could you please fix it :( otherwise I am gonna have to manually set it every time for ios and Android and I might forget.

Thanks

**Comment by EddyVerbruggen** [comment]
Please check 1.2.0 (also available on npm) and close if it's working nicely. Thanks for bringing this kind of usage to my attention!

**Comment by Daxito** [comment]
Works perfect! Closing.
