### ISSUE TITLE
NSBundle.mainBundle() error using TNS 2.3.0 and Xcode 8

### ISSUE THREAD

**Issue by DomGaud** [EddyVerbruggen/nativescript-appversion#6]
After upgrading to Nativescript 2.3.0 and Xcode 8 the following error occurs:

`TypeError: NSBundle.mainBundle is not a function. (In 'NSBundle.mainBundle()', 'NSBundle.mainBundle' is an instance of NSBundle)

file:///app/tns_modules/zone.js/dist/zone-node.js:442:27: Unhandled Promise rejection: NSBundle.mainBundle is not a function. (In 'NSBundle.mainBundle()', 'NSBundle.mainBundle' is an instance of NSBundle) ; Zone: <root> ; Task: Promise.then ; Value: TypeError: NSBundle.mainBundle is not a function. (In 'NSBundle.mainBundle()', 'NSBundle.mainBundle' is an instance of NSBundle) file:///app/tns_modules/nativescript-appversion/appversion.js:17:34
`

**Comment by EddyVerbruggen** [comment]
Ah yes, iOS 10 changed a few things (methods vs properties). Thx for letting me know.

**Comment by DomGaud** [comment]
Good point! I have test and it works using a property instead of a method.

Solution - change from using a method:

``` Javascript
NSBundle.mainBundle().
```

to a property

``` Javascript
NSBundle.mainBundle.
```

**Comment by EddyVerbruggen** [comment]
Thanks for confirming that! I've adjusted the plugin code and it should now be compatible with iOS 10, and backward compatible with any lower version.

It's recommended to upgrade to plugin version 1.3.1 (which requires {N} 2.3.0 (which you already have)).
